[package]
name = "rust-gmp"
version = "0.2.9"
authors = [ "thestinger <danielmicay@gmail.com>", "Bartłomiej Kamiński <fizyk20@gmail.com>" ]
description = "Rust bindings for GMP"
repository = "https://github.com/fizyk20/rust-gmp"
license-file = "LICENSE"
keywords = [ "gmp", "multi", "precision", "arithmetic", "bignum" ]

[lib]
name = "gmp"

[dependencies]
libc = "*"
quickcheck = "0.2"
quickcheck_macros = "0.2"
